package com.company;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class myForm {
    private JPanel myFrame;
    private JButton calculate;
    private JTextField yTextField;
    private JTextField xTextField;

    private myForm() {
        calculate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String result = calculate(Float.parseFloat(xTextField.getText()), Float.parseFloat(yTextField.getText()));
                showResult(result);
            }
        });
        calculate.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String result = calculate(Float.parseFloat(xTextField.getText()), Float.parseFloat(yTextField.getText()));
                    showResult(result);
                }
            }
        });


        yTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String result = calculate(Float.parseFloat(xTextField.getText()), Float.parseFloat(yTextField.getText()));
                    showResult(result);
                }
            }
        });
    }

    private void showResult(String result) {
        JOptionPane.showMessageDialog(null, result);
    }

    private String calculate(float x, float y) {
        String result = "";
        if (x > 0 && y > 0) {
            if ((x * x >= (0.5 - y * y)) && (x * x <= 1.0 - y * y)) {
                result = "TARGET!";
            } else {
                result = "PAST!";
            }
        } else {
            result = "PAST!";
        }
        return result;
    }

    public static void main(String[] args) {
        class MyWindowApp extends JFrame {
            private MyWindowApp() {
                super("Calculation result");
                setContentPane(new myForm().myFrame);
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                pack();
                setVisible(true);
            }
        }
        MyWindowApp app = new MyWindowApp();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myFrame = new JPanel();
        myFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        xTextField = new JTextField();
        myFrame.add(xTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        yTextField = new JTextField();
        myFrame.add(yTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        calculate = new JButton();
        calculate.setText("MAGIC!");
        myFrame.add(calculate, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myFrame;
    }

}
